### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by exclu5iv3** [Cy4n1d3/PokeminerSpawns#8]
I am getting this error after pokeminer update(v0.5.2).

Traceback (most recent call last):
  File "spawn_location.py", line 59, in <module>
    poke_id, spawn_id, expire_timestamp, despawn, coord_lat, coord_long = entry[1:]
ValueError: too many values to unpack

**Comment by Cy4n1d3** [comment]
Pokeminer got a new database structure.
I'm no expert at this (and not running Pokeminer actively right now) but I have an idea for an easy fix.

**Comment by exclu5iv3** [comment]
I have zero experience in coding and python etc. So you telling that reason for this is database structure change solved my problem. I can just modify the database to look like old one. 
Seems to work.

Thanks.

**Comment by Cy4n1d3** [comment]
Don't do such things, at least not in a productive environment!
Pokeminer won't be able to correctly insert all needed values else.

I've pushed a fix, do you have a backup of your database?
If so, please revert to that backup and test the fix, should work with the old version and the current one.
In the future, it will throw an error if something looks wrong.

**Comment by exclu5iv3** [comment]
Yes i have a backup. Tested it and single spawn points are okey. (Spawns_number) . In spawns_all nothing shows up, same for spawns if i press all spawn locations.

**Comment by Cy4n1d3** [comment]
I'll set up a local Pokeminer install once again and see if I can find the culprit.
Updated some other things in the meantime:
 - generated files can now be found in 'output' folder
 - added static files and locales to this git as they are no longer part of Pokeminer
 - you can use your backup database for now by putting it into the `/spawns` directory (or whereever this script is located for you)

**Comment by exclu5iv3** [comment]
Everything works now. Got this error: 
Traceback (most recent call last):
  File "spawn_location.py", line 171, in <module>
    with open(u'output/spawns{}.html'.format(CONFIG[u'suffix']), 'w') as f:
IOError: [Errno 2] No such file or directory: u'output/spawns.html'

Solved it by greating folder output and copied spawns.html to there from templates.

**Comment by Cy4n1d3** [comment]
Of course, damn it.
Pushed a fix for that error :)
